# Generated by Django 6.0.2 on 2026-03-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_balance_balancetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUPPORT', 'Support'), ('MANAGER', 'Manager'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
