# Generated by Django 6.0.2 on 2026-03-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
