# Generated by Django 6.0.2 on 2026-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='balance_deducted',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='duplicate_numbers',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='invalid_numbers',
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='api_message_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='campaign_media/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignrecipient',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
